[build]
command="echo 'Nothing to build'"
publish="public/"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''

[[edge_functions]]
  path = "/chunked/*"
  function = "cors-preflight"

[[edge_functions]]
  path = "/full/*"
  function = "cors-preflight"

[[headers]]
  for = "/full/*"
  [headers.values]
    cache-control = "max-age=600"
    access-control-allow-origin = "*"

[[headers]]
  for = "/chunked/*"
  [headers.values]
    cache-control = "max-age=600"
    access-control-allow-origin = "*"
